/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SciPlot {
        "height": number;
        "lineColor": string;
        "source": string;
        "timeViewMinutes": number;
        "width": number;
    }
}
declare global {
    interface HTMLSciPlotElement extends Components.SciPlot, HTMLStencilElement {
    }
    var HTMLSciPlotElement: {
        prototype: HTMLSciPlotElement;
        new (): HTMLSciPlotElement;
    };
    interface HTMLElementTagNameMap {
        "sci-plot": HTMLSciPlotElement;
    }
}
declare namespace LocalJSX {
    interface SciPlot {
        "height"?: number;
        "lineColor"?: string;
        "source": string;
        "timeViewMinutes"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "sci-plot": SciPlot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sci-plot": LocalJSX.SciPlot & JSXBase.HTMLAttributes<HTMLSciPlotElement>;
        }
    }
}
