/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SciPlot {
        "height": number;
        "lineColor": string;
        "source": string;
        "timeViewMinutes": number;
        "width": number;
    }
    interface SciTerminal {
    }
    interface SciThree {
    }
}
declare global {
    interface HTMLSciPlotElement extends Components.SciPlot, HTMLStencilElement {
    }
    var HTMLSciPlotElement: {
        prototype: HTMLSciPlotElement;
        new (): HTMLSciPlotElement;
    };
    interface HTMLSciTerminalElement extends Components.SciTerminal, HTMLStencilElement {
    }
    var HTMLSciTerminalElement: {
        prototype: HTMLSciTerminalElement;
        new (): HTMLSciTerminalElement;
    };
    interface HTMLSciThreeElement extends Components.SciThree, HTMLStencilElement {
    }
    var HTMLSciThreeElement: {
        prototype: HTMLSciThreeElement;
        new (): HTMLSciThreeElement;
    };
    interface HTMLElementTagNameMap {
        "sci-plot": HTMLSciPlotElement;
        "sci-terminal": HTMLSciTerminalElement;
        "sci-three": HTMLSciThreeElement;
    }
}
declare namespace LocalJSX {
    interface SciPlot {
        "height"?: number;
        "lineColor"?: string;
        "source": string;
        "timeViewMinutes"?: number;
        "width"?: number;
    }
    interface SciTerminal {
    }
    interface SciThree {
    }
    interface IntrinsicElements {
        "sci-plot": SciPlot;
        "sci-terminal": SciTerminal;
        "sci-three": SciThree;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sci-plot": LocalJSX.SciPlot & JSXBase.HTMLAttributes<HTMLSciPlotElement>;
            "sci-terminal": LocalJSX.SciTerminal & JSXBase.HTMLAttributes<HTMLSciTerminalElement>;
            "sci-three": LocalJSX.SciThree & JSXBase.HTMLAttributes<HTMLSciThreeElement>;
        }
    }
}
